### PR TITLE
Custom tooling 

### PR DESCRIPTION
**Pull request by advaithm**
I hope this pull request can start a line of custom tooling for distro delves.
This PR adds a custom tool called stress_cpu_x64. The program inefficiently(uses more CPU bandwidth then required) calculates the first 10 million primes. The main aim is to  use up as much CPU bandwidth as possible. This is too be run while egee uses stuff like Youtube and text-editors to simulate a regular user using their system while it is under-load.

I have included the source files as well as the prebuilt binary as due to GLIBC mismatches on some distros the prebuilt may not work. only deps required are gcc and make(if you do want to look up the command to build). 
I have also added a outro segment rating the difficulty of solving issues encountered during the distro delve as this will influence peoples likelihood too try out a distro.

### CODE REVIEW

**Comment by egee-irl** [comment]
> How the user experience is when stressing the CPU using stress_cpu_x64(for x86_64 systems)

This is a really interesting idea, I'll have to play around with it before deciding to put it into a Distro Delves episode. Maybe we can try it on stream sometime?

> Rate fixing issues found in the review on a scale of 1 to 10. 1 the issue resolved itself. 10 unfixable

I've avoided ranking issues and distros because I don't want the series to turn into a "recommended distros" style of show. Besides, the rankings would only make sense for Linux distros and we cover more than just Linux on Distro Delves.

**Comment by advaithm** [comment]
> This is a really interesting idea, I'll have to play around with it before deciding to put it into a Distro Delves episode. Maybe we can try it on stream sometime?

Sure I would love to see what you think about the program. Its not exactly POSIX compliant I'll be fixing that in later versions.

> I've avoided ranking issues and distros because I don't want the series to turn into a "recommended distros" style of show. Besides, the rankings would only make sense for Linux distros and we cover more than just Linux on Distro Delves.

Oh okay I'll remove that from my PR.

**Comment by egee-irl** [comment]
Don't throwaway the code though - I'd like to try it sometime soon. It's a very interesting test, maybe for the performance benchmark non-show.

**Comment by advaithm** [comment]
one thing I should make clear is that this isn't a bench mark in the conventional sense. Its more of a thing that stress CPUs. The idea is to see how a distro holds up as the % of  the cpu usable decreases

**Comment by egee-irl** [comment]
@advaithm Is this still good? Should we look at it this Saturday?

**Comment by advaithm** [comment]
This is still good you can look at it on Saturday

**Comment by egee-irl** [comment]
@advaithm What do you think we should do with this?

**Comment by advaithm** [comment]
Honestly I dunno

**Comment by egee-irl** [comment]
Let's get yo name on the contributors list!

**Pull request merged**
